name: CI

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit == false
        run: yarn install --frozen-lockfile

  format:
    needs: install

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run formatter
        id: format
        run: npx prettier -w .

      - run: echo  ${{ github.payload.pull_request.head.ref }}

      - name: Commit changes
        if: steps.format.outputs.changes_detected == true
        run: |
          git add .
          git config user.email "bot@green-got.com"
          git config user.name "Green Got Bot"
          git commit --amend --no-edit
          git push origin HEAD:${github.payload.pull_request.head.ref} -f
