name: Continuous Delivery

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  install:
    uses: green-got/green-got-mono-repo/.github/workflows/install.yml@main
  cdk:
    needs: [format, lint, type-check, test]
    uses: green-got/green-got-mono-repo/.github/workflows/cdk.yml@main
    with:
      env: prod
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  assets:
    needs: [format, lint, type-check, test]
    uses: green-got/green-got-mono-repo/.github/workflows/pulumi.yml@main
    with:
      stack: green-got/assets/prod
      workspace: assets
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  analytics:
    needs: [format, lint, type-check, test]
    uses: green-got/green-got-mono-repo/.github/workflows/pulumi.yml@staging
    with:
      stack: green-got/analytics/prod
      workspace: analytics
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  webhooks:
    needs: [format, lint, type-check, test]
    uses: green-got/green-got-mono-repo/.github/workflows/pulumi.yml@staging
    with:
      stack: green-got/web-hooks/prod
      workspace: webhooks
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  ensure-indexes:
    needs: [format, lint, type-check, test]
    uses: green-got/green-got-mono-repo/.github/workflows/ensure-indexes.yml@main
    secrets:
      MONGO_URI: ${{ secrets.STAGING_MONGO_URI }}
