name: Deploy

on:
  create:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/deployment') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: deployment

      - name: Reset branch
        run: |
          echo github.ref
          git reset --hard origin/main
          git push -f
