name: Deploy

on:
  push:
    branches-ignore:
      - "!main"
    tags:
      - deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: deployment
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git reset --hard main
          git push --force
