name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Wireguard
      run: sudo apt-get install wireguard
    - name: Copy WireGuard config
      run: sudo echo "$WIREGUARD_CONFIG" > /etc/wireguard/wg0.conf
      env:
        WIREGUARD_CONFIG: ${{secrets.WIREGUARD_CONFIG}}
    - name: Start Wireguard
      run: wg-quick up wg0
