name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Wireguard
      run: sudo apt-get install wireguard
    - name: Start Wireguard
      run: wg-quick up wg0
