name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Wireguard
      run: sudo apt-get install wireguard
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create WireGuard config
      run: |
        sed -i -e "s@{{WIREGUARD_PRIVATE_KEY}}@${{ secrets.WIREGUARD_PRIVATE_KEY }}@" wg0.conf
        sed -i -e "s@{{WIREGUARD_SERVER_PUBLIC_KEY}}@${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}@" wg0.conf
        sed -i -e "s@{{WIREGUARD_SERVER_ENDPOINT}}@${{ secrets.WIREGUARD_SERVER_ENDPOINT }}@" wg0.conf
        sudo cp wg0.conf /etc/wireguard/
    - name: Create resolvconf symlink
      run: ln -s /usr/bin/resolvectl /usr/local/bin/resolvconf
    - name: Start Wireguard
      run: wg-quick up wg0
    - name: Stop Wireguard
      run: wg-quick down wg0

